<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE object
[
   <!ELEMENT object (#PCDATA|object)*>
   <!ATTLIST object name      CDATA #REQUIRED>
   <!ATTLIST object class     CDATA #REQUIRED>
   <!ATTLIST object primitive CDATA "no">
   <!ATTLIST object array     CDATA "no">   <!-- the dimensions of the array; no=0, yes=1 -->
   <!ATTLIST object null      CDATA "no">
   <!ATTLIST object version   CDATA "3.8.6">
]
>

<object class="weka.classifiers.meta.LogitBoost" name="__root__" version="3.8.6">
   <object class="boolean" name="debug" primitive="yes">false</object>
   <object array="yes" class="java.lang.String" name="options">
      <object class="java.lang.String" name="0">-P</object>
      <object class="java.lang.String" name="1">100</object>
      <object class="java.lang.String" name="2">-L</object>
      <object class="java.lang.String" name="3">-1.7976931348623157E308</object>
      <object class="java.lang.String" name="4">-H</object>
      <object class="java.lang.String" name="5">1.0</object>
      <object class="java.lang.String" name="6">-Z</object>
      <object class="java.lang.String" name="7">3.0</object>
      <object class="java.lang.String" name="8">-O</object>
      <object class="java.lang.String" name="9">1</object>
      <object class="java.lang.String" name="10">-E</object>
      <object class="java.lang.String" name="11">1</object>
      <object class="java.lang.String" name="12">-S</object>
      <object class="java.lang.String" name="13">1</object>
      <object class="java.lang.String" name="14">-I</object>
      <object class="java.lang.String" name="15">10</object>
      <object class="java.lang.String" name="16">-W</object>
      <object class="java.lang.String" name="17">weka.classifiers.trees.REPTree</object>
      <object class="java.lang.String" name="18">--</object>
      <object class="java.lang.String" name="19">-M</object>
      <object class="java.lang.String" name="20">2</object>
      <object class="java.lang.String" name="21">-V</object>
      <object class="java.lang.String" name="22">0.001</object>
      <object class="java.lang.String" name="23">-N</object>
      <object class="java.lang.String" name="24">3</object>
      <object class="java.lang.String" name="25">-S</object>
      <object class="java.lang.String" name="26">1</object>
      <object class="java.lang.String" name="27">-L</object>
      <object class="java.lang.String" name="28">-1</object>
      <object class="java.lang.String" name="29">-I</object>
      <object class="java.lang.String" name="30">0.0</object>
   </object>
</object>
